### ISSUE TITLE
Conversion between KB and B is not correct

### ISSUE THREAD

**Issue by fantasy8-me** [jvecchioli/byte-converter#1]
```
converter(1, 'KB', 'B') //return 100
````

**Comment by jvecchioli** [comment]
Thank you for filing the issue.
I fixed the conversion by changing the unit-description.js file.
Some more unit tests are available.

**Comment by fantasy8-me** [comment]
Thanks for the prompt action, could you please bump the version to 0.14

**Comment by jvecchioli** [comment]
Bump done, and published on npmjs. Cheers.
